<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ArrowLeft, Close, Delete, Document, Download, EditPen, Plus, UploadFilled } from '@element-plus/icons-vue'
import { useRouter } from 'vue-router'
import AppShell from '@/components/AppShell.vue'
import { createCollectionTask, deleteCollectionTask, downloadSubmissionAttachment, exportTask, fetchCollectionTasks, fetchMySubmission, fetchTaskSubmissions, returnTaskSubmission, saveMySubmission, updateCollectionTask, type CollectionField, type CollectionTask, type Submission, type TaskForm } from '@/api/collections'
import { useAuthStore } from '@/stores/auth'

const auth = useAuthStore(); const router = useRouter(); const tasks = ref<CollectionTask[]>([]); const selected = ref<CollectionTask>(); const loading = ref(false); const error = ref(''); const editorOpen = ref(false); const editingId = ref<number>(); const submissions = ref<Submission[]>([]); const missing = ref<{ student_id: number; student_name: string }[]>([]); const overdue = ref<{ student_id: number; student_name: string }[]>([]); const mine = ref<Submission | null>(); const answers = ref<Record<string, string>>({}); const attachment = ref<File>(); const saving = ref(false)
const emptyForm = (): TaskForm => ({ title: '', description: '', fields: [{ id: crypto.randomUUID(), label: '', type: 'text', required: true, options: [] }], status: 'draft', deadline: '', attachment_required: false, allow_modify: true })
const form = ref<TaskForm>(emptyForm()); const statusText = { draft: '草稿', published: '进行中', closed: '已结束' }; const submissionText = { draft: '未提交', submitted: '已提交', returned: '已退回' }
const pendingCount = computed(() => tasks.value.filter((item) => item.my_status !== 'submitted').length)
async function load() { loading.value = true; error.value = ''; try { tasks.value = await fetchCollectionTasks() } catch (e: any) { error.value = e.response?.data?.detail ?? '任务加载失败' } finally { loading.value = false } }
async function selectTask(item: CollectionTask) { selected.value = item; error.value = ''; if (auth.role === 'secretary') { const data = await fetchTaskSubmissions(item.id); submissions.value = data.submissions; missing.value = data.missing; overdue.value = data.overdue } else { mine.value = await fetchMySubmission(item.id); answers.value = { ...(mine.value?.answers ?? {}) }; attachment.value = undefined } }
function openCreate() { editingId.value = undefined; form.value = emptyForm(); editorOpen.value = true }
function openEdit(item: CollectionTask) { editingId.value = item.id; form.value = { title: item.title, description: item.description, fields: item.fields.map((field) => ({ ...field, options: [...field.options] })), status: item.status, deadline: item.deadline ?? '', attachment_required: item.attachment_required, allow_modify: item.allow_modify }; editorOpen.value = true }
function addField() { form.value.fields.push({ id: crypto.randomUUID(), label: '', type: 'text', required: false, options: [] }) }
function removeField(index: number) { if (form.value.fields.length > 1) form.value.fields.splice(index, 1) }
function setFieldType(field: CollectionField) { field.options = field.type === 'single' ? ['选项一', '选项二'] : [] }
function setOptions(field: CollectionField, value: string) { field.options = value.split('\n').map((item) => item.trim()).filter(Boolean) }
async function saveTask() { saving.value = true; error.value = ''; try { if (editingId.value) await updateCollectionTask(editingId.value, form.value); else await createCollectionTask(form.value); editorOpen.value = false; await load() } catch (e: any) { error.value = e.response?.data?.detail ?? '任务保存失败' } finally { saving.value = false } }
async function removeTask(item: CollectionTask) { if (!confirm(`确定删除“${item.title}”及其全部提交记录吗？`)) return; await deleteCollectionTask(item.id); selected.value = undefined; await load() }
async function changeStatus(item: CollectionTask, status: CollectionTask['status']) { await updateCollectionTask(item.id, { title: item.title, description: item.description, fields: item.fields, status, deadline: item.deadline ?? '', attachment_required: item.attachment_required, allow_modify: item.allow_modify }); await load(); selected.value = tasks.value.find((task) => task.id === item.id) }
async function saveSubmission(submit: boolean) { if (!selected.value) return; saving.value = true; error.value = ''; try { mine.value = await saveMySubmission(selected.value.id, answers.value, submit, attachment.value); attachment.value = undefined; await load(); selected.value = tasks.value.find((item) => item.id === selected.value?.id); alert(submit ? '提交成功' : '草稿已保存') } catch (e: any) { error.value = e.response?.data?.detail ?? '保存失败' } finally { saving.value = false } }
async function sendBack(item: Submission) { if (!selected.value) return; const reason = prompt(`退回“${item.student_name}”的提交，请填写原因：`); if (!reason?.trim()) return; await returnTaskSubmission(selected.value.id, item.id, reason); await selectTask(selected.value) }
function isOverdue(task: CollectionTask) { return Boolean(task.deadline && new Date(task.deadline) < new Date()) }
onMounted(load)
</script>

<template>
  <AppShell :role-label="auth.role === 'secretary' ? '团支书端' : '学生端'" active-label="信息收集">
    <button class="back-link" type="button" @click="router.push(auth.role === 'secretary' ? '/secretary' : '/student')"><ArrowLeft />返回工作台</button>
    <section class="tool-heading"><span class="module-icon blue"><Document /></span><div><p class="eyebrow">班级协作</p><h1>信息收集</h1><p>{{ auth.role === 'secretary' ? '创建表单任务并掌握全班提交进度。' : `查看本班任务，目前有 ${pendingCount} 项待完成。` }}</p></div></section>
    <p v-if="error" class="error-message" role="alert">{{ error }}</p>
    <div class="notice-toolbar"><div><strong>{{ tasks.length }}</strong><span>项任务</span></div><button v-if="auth.role === 'secretary'" class="primary-action" type="button" @click="openCreate"><Plus />新建收集任务</button></div>
    <section class="notice-layout collection-layout">
      <div class="notice-list" :aria-busy="loading">
        <button v-for="item in tasks" :key="item.id" :class="['notice-list-item', { active: selected?.id === item.id }]" type="button" @click="selectTask(item)"><span :class="['status-chip', item.status]">{{ statusText[item.status] }}</span><strong>{{ item.title }}</strong><p>{{ item.description || '未填写说明' }}</p><small v-if="auth.role === 'secretary'">已提交 {{ item.submitted_count }}/{{ item.student_count }}</small><small v-else>{{ item.my_status ? submissionText[item.my_status] : '待填写' }}<template v-if="isOverdue(item)"> · 已逾期</template></small></button>
        <p v-if="loading" class="empty-copy">正在加载任务…</p><p v-else-if="!tasks.length" class="empty-copy">暂时没有收集任务。</p>
      </div>
      <article v-if="selected" class="notice-detail collection-detail"><div class="notice-detail-heading"><div><span :class="['status-chip', selected.status]">{{ statusText[selected.status] }}</span><h2>{{ selected.title }}</h2></div><button class="icon-action" aria-label="关闭详情" @click="selected = undefined"><Close /></button></div><p class="notice-content">{{ selected.description || '暂无任务说明' }}</p><dl><div><dt>截止时间</dt><dd>{{ selected.deadline ? new Date(selected.deadline).toLocaleString() : '未设置' }}</dd></div><div><dt>附件要求</dt><dd>{{ selected.attachment_required ? '必须上传' : '可选' }}</dd></div></dl>
        <template v-if="auth.role === 'secretary'"><div class="detail-actions"><button class="secondary-action" @click="openEdit(selected)"><EditPen />编辑</button><button v-if="selected.status !== 'published'" class="primary-action" @click="changeStatus(selected, 'published')">发布</button><button v-if="selected.status === 'published'" class="secondary-action" @click="changeStatus(selected, 'closed')">结束收集</button><button class="secondary-action" @click="exportTask(selected.id, selected.title)"><Download />导出汇总</button><button class="danger-action" @click="removeTask(selected)"><Delete />删除</button></div><h3 class="subsection-title">提交情况</h3><div class="submission-list"><article v-for="item in submissions" :key="item.id" class="submission-card"><header><strong>{{ item.student_name }}</strong><span :class="['status-chip', item.status]">{{ submissionText[item.status] }}</span></header><p v-for="field in selected.fields" :key="field.id"><b>{{ field.label }}：</b>{{ item.answers[field.id] || '未填写' }}</p><p v-if="item.return_reason" class="return-note">退回原因：{{ item.return_reason }}</p><div class="detail-actions"><button v-if="item.attachment_name" class="secondary-action" @click="downloadSubmissionAttachment(selected.id, item)"><Download />{{ item.attachment_name }}</button><button v-if="item.status === 'submitted'" class="secondary-action" @click="sendBack(item)">退回修改</button></div></article><p v-if="!submissions.length" class="empty-copy">还没有学生保存或提交。</p></div><div v-if="missing.length" class="missing-students"><h3>尚未填写（{{ missing.length }}）</h3><p>{{ missing.map((item) => item.student_name).join('、') }}</p></div><div v-if="overdue.length" class="missing-students overdue-students"><h3>已经逾期（{{ overdue.length }}）</h3><p>{{ overdue.map((item) => item.student_name).join('、') }}</p></div></template>
        <form v-else class="student-collection-form" @submit.prevent="saveSubmission(true)"><p v-if="mine?.status === 'returned'" class="return-note">已退回：{{ mine.return_reason }}</p><label v-for="field in selected.fields" :key="field.id">{{ field.label }}<span v-if="field.required"> *</span><input v-if="field.type === 'text'" v-model.trim="answers[field.id]" :required="field.required" /><input v-else-if="field.type === 'date'" v-model="answers[field.id]" type="date" :required="field.required" /><select v-else v-model="answers[field.id]" :required="field.required"><option value="">请选择</option><option v-for="option in field.options" :key="option">{{ option }}</option></select></label><label>上传附件<span v-if="selected.attachment_required"> *</span><input type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png" @change="attachment = ($event.target as HTMLInputElement).files?.[0]" /><small v-if="mine?.attachment_name">当前文件：{{ mine.attachment_name }}</small></label><footer><button class="secondary-action" type="button" :disabled="saving || (mine?.status === 'submitted' && !selected.allow_modify)" @click="saveSubmission(false)">保存草稿</button><button class="primary-action" type="submit" :disabled="saving || (mine?.status === 'submitted' && !selected.allow_modify)">{{ mine?.status === 'submitted' ? '更新提交' : mine?.status === 'returned' ? '重新提交' : '确认提交' }}</button></footer><p v-if="mine?.status === 'submitted' && !selected.allow_modify" class="helper-copy">该任务提交后不允许修改。</p></form>
      </article><div v-else class="notice-placeholder"><Document /><p>选择一项任务查看详情</p></div>
    </section>
    <div v-if="editorOpen" class="modal-backdrop" @click.self="editorOpen = false"><section class="editor-modal collection-editor" role="dialog" aria-modal="true" aria-labelledby="collection-editor-title"><header><div><p class="eyebrow">团支书端</p><h2 id="collection-editor-title">{{ editingId ? '编辑收集任务' : '新建收集任务' }}</h2></div><button class="icon-action" aria-label="关闭编辑窗口" @click="editorOpen = false"><Close /></button></header><label>任务标题<input v-model.trim="form.title" maxlength="200" /></label><label>任务说明<textarea v-model.trim="form.description" rows="3"></textarea></label><div class="field-builder"><div class="field-builder-title"><strong>表单字段</strong><button class="secondary-action" type="button" @click="addField"><Plus />添加字段</button></div><article v-for="(field, index) in form.fields" :key="field.id" class="field-row"><input v-model.trim="field.label" placeholder="字段名称" /><select v-model="field.type" @change="setFieldType(field)"><option value="text">文本</option><option value="date">日期</option><option value="single">单选</option></select><label class="inline-check"><input v-model="field.required" type="checkbox" />必填</label><button class="icon-action" type="button" aria-label="删除字段" @click="removeField(index)"><Delete /></button><textarea v-if="field.type === 'single'" :value="field.options.join('\n')" rows="2" placeholder="每行一个选项" @input="setOptions(field, ($event.target as HTMLTextAreaElement).value)"></textarea></article></div><label>截止时间<input v-model="form.deadline" type="datetime-local" /></label><div class="option-row"><label class="inline-check"><input v-model="form.attachment_required" type="checkbox" />要求上传附件</label><label class="inline-check"><input v-model="form.allow_modify" type="checkbox" />提交后允许修改</label></div><label>保存状态<select v-model="form.status"><option value="draft">保存草稿</option><option value="published">立即发布</option><option v-if="editingId" value="closed">结束收集</option></select></label><footer><button class="secondary-action" @click="editorOpen = false">取消</button><button class="primary-action" :disabled="saving || !form.title || form.fields.some((field) => !field.label)" @click="saveTask">保存任务</button></footer></section></div>
  </AppShell>
</template>
